-- Generated from drizzle MySQL schema.ts to PostgreSQL DDL
BEGIN;
DO $$ BEGIN
    CREATE TYPE "users_role_enum" AS ENUM ('user', 'admin', 'superadmin');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "users_plan_enum" AS ENUM ('free', 'premium');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "admin_audit_logs_action_enum" AS ENUM ('PROMOTE_ADMIN', 'DEMOTE_ADMIN', 'PROMOTE_SUPERADMIN', 'DEMOTE_SUPERADMIN');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "subscription_plans_interval_enum" AS ENUM ('month', 'year');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "user_subscriptions_status_enum" AS ENUM ('active', 'canceled', 'past_due', 'trialing');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "user_profiles_gender_enum" AS ENUM ('male', 'female', 'other', 'prefer_not_to_say');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "connections_status_enum" AS ENUM ('active', 'blocked');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "connection_requests_status_enum" AS ENUM ('pending', 'accepted', 'rejected');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "reports_status_enum" AS ENUM ('pending', 'reviewed', 'resolved', 'dismissed');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "course_purchases_status_enum" AS ENUM ('pending', 'completed', 'failed', 'refunded');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "subscriptions_plan_enum" AS ENUM ('free', 'basic', 'premium', 'vip');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "subscriptions_status_enum" AS ENUM ('active', 'paused', 'cancelled', 'expired', 'trial');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "payment_history_status_enum" AS ENUM ('pending', 'completed', 'failed', 'refunded');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "referrals_status_enum" AS ENUM ('pending', 'confirmed', 'cancelled');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "referrals_planPurchased_enum" AS ENUM ('basic', 'premium', 'vip');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "pointsTransactions_type_enum" AS ENUM ('referral_bonus', 'monthly_bonus', 'cashback_redeemed', 'admin_adjustment', 'free_month_applied');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "cashbackRequests_status_enum" AS ENUM ('pending', 'approved', 'rejected', 'paid');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "cashbackRequests_paymentMethod_enum" AS ENUM ('pix', 'bank_transfer', 'credit_account');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "adminInvites_role_enum" AS ENUM ('admin', 'superadmin');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "appointments_status_enum" AS ENUM ('scheduled', 'confirmed', 'completed', 'cancelled', 'no_show');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE "notifications_type_enum" AS ENUM ('info', 'success', 'warning', 'error', 'appointment');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "openId" VARCHAR(64) UNIQUE,
  "name" TEXT,
  "email" VARCHAR(320) NOT NULL UNIQUE,
  "passwordHash" VARCHAR(255),
  "emailVerified" INTEGER NOT NULL DEFAULT 0,
  "loginMethod" VARCHAR(64) NOT NULL DEFAULT 'email',
  "role" "users_role_enum" NOT NULL DEFAULT 'user',
  "plan" "users_plan_enum" NOT NULL DEFAULT 'free',
  "stripeCustomerId" VARCHAR(255) UNIQUE,
  "referralCode" VARCHAR(32) UNIQUE,
  "referredBy" VARCHAR(32),
  "pointsBalance" INTEGER NOT NULL DEFAULT 0,
  "freeMonthsRemaining" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "lastSignedIn" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "admin_audit_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "action" "admin_audit_logs_action_enum" NOT NULL,
  "performedByUserId" INTEGER NOT NULL,
  "targetUserId" INTEGER NOT NULL,
  "ip" VARCHAR(45),
  "userAgent" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "courses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "title" VARCHAR(255) NOT NULL,
  "slug" VARCHAR(255) NOT NULL UNIQUE,
  "description" TEXT,
  "thumbnail" TEXT,
  "instructorId" INTEGER NOT NULL,
  "price" INTEGER,
  "isPublished" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "course_modules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "courseId" INTEGER NOT NULL,
  "title" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "order" INTEGER NOT NULL,
  "isPublished" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "lessons" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "courseId" INTEGER NOT NULL,
  "moduleId" INTEGER,
  "title" VARCHAR(255) NOT NULL,
  "order" INTEGER NOT NULL,
  "description" TEXT,
  "videoProvider" VARCHAR(50),
  "videoAssetId" VARCHAR(255),
  "videoPlaybackUrl" TEXT,
  "duration" INTEGER,
  "isPublished" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "enrollments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "courseId" INTEGER NOT NULL,
  "progress" INTEGER NOT NULL DEFAULT 0,
  "completedLessons" TEXT,
  "enrolledAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "lastAccessedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "subscription_plans" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "name" VARCHAR(100) NOT NULL,
  "slug" VARCHAR(100) NOT NULL UNIQUE,
  "description" TEXT,
  "price" INTEGER NOT NULL,
  "interval" "subscription_plans_interval_enum" NOT NULL,
  "features" TEXT,
  "maxCourses" INTEGER,
  "hasVRAccess" INTEGER NOT NULL DEFAULT 0,
  "hasLiveSupport" INTEGER NOT NULL DEFAULT 0,
  "stripePriceId" VARCHAR(255),
  "isActive" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "user_subscriptions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "planId" INTEGER NOT NULL,
  "stripeCustomerId" VARCHAR(255),
  "stripeSubscriptionId" VARCHAR(255),
  "status" "user_subscriptions_status_enum" NOT NULL,
  "currentPeriodStart" TIMESTAMPTZ,
  "currentPeriodEnd" TIMESTAMPTZ,
  "cancelAtPeriodEnd" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "course_reviews" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "courseId" INTEGER NOT NULL,
  "userId" INTEGER NOT NULL,
  "rating" INTEGER NOT NULL,
  "comment" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "ebooks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "title" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "fileUrl" TEXT NOT NULL,
  "fileKey" VARCHAR(500) NOT NULL,
  "thumbnail" TEXT,
  "courseId" INTEGER,
  "isPublished" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "user_badges" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "badgeType" VARCHAR(100) NOT NULL,
  "badgeName" VARCHAR(255) NOT NULL,
  "badgeDescription" TEXT,
  "badgeIcon" TEXT,
  "earnedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "certificates" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "courseId" INTEGER NOT NULL,
  "certificateNumber" VARCHAR(100) NOT NULL UNIQUE,
  "pdfUrl" TEXT,
  "issuedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "user_profiles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL UNIQUE,
  "bio" TEXT,
  "avatar" TEXT,
  "phoneNumber" VARCHAR(20),
  "birthDate" DATE,
  "gender" "user_profiles_gender_enum",
  "address" VARCHAR(255),
  "city" VARCHAR(100),
  "state" VARCHAR(2),
  "zipCode" VARCHAR(10),
  "country" VARCHAR(100) NOT NULL DEFAULT 'Brazil',
  "interests" TEXT,
  "goals" TEXT,
  "isPublic" INTEGER NOT NULL DEFAULT 0,
  "showCity" INTEGER NOT NULL DEFAULT 0,
  "emergencyContactName" VARCHAR(255),
  "emergencyContactPhone" VARCHAR(20),
  "medicalNotes" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "connections" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId1" INTEGER NOT NULL,
  "userId2" INTEGER NOT NULL,
  "status" "connections_status_enum" NOT NULL DEFAULT 'active',
  "connectedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "connection_requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "fromUserId" INTEGER NOT NULL,
  "toUserId" INTEGER NOT NULL,
  "message" TEXT,
  "status" "connection_requests_status_enum" NOT NULL DEFAULT 'pending',
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "respondedAt" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "reports" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "reporterId" INTEGER NOT NULL,
  "reportedUserId" INTEGER NOT NULL,
  "reason" VARCHAR(100) NOT NULL,
  "description" TEXT,
  "status" "reports_status_enum" NOT NULL DEFAULT 'pending',
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "reviewedAt" TIMESTAMPTZ,
  "reviewedBy" INTEGER
);

CREATE TABLE IF NOT EXISTS "moderation_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "adminId" INTEGER NOT NULL,
  "targetUserId" INTEGER NOT NULL,
  "action" VARCHAR(100) NOT NULL,
  "reason" TEXT,
  "duration" INTEGER,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "conversations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "user1Id" INTEGER NOT NULL,
  "user2Id" INTEGER NOT NULL,
  "lastMessageAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "messages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "conversationId" INTEGER NOT NULL,
  "senderId" INTEGER NOT NULL,
  "receiverId" INTEGER NOT NULL,
  "content" TEXT NOT NULL,
  "isRead" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "email_verification_tokens" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "token" VARCHAR(255) NOT NULL UNIQUE,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "password_reset_tokens" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "token" VARCHAR(255) NOT NULL UNIQUE,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "used" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "refresh_tokens" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "token" VARCHAR(500) NOT NULL UNIQUE,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "revoked" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "course_purchases" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "courseId" INTEGER NOT NULL,
  "amount" INTEGER NOT NULL,
  "currency" VARCHAR(3) NOT NULL DEFAULT 'BRL',
  "stripePaymentIntentId" VARCHAR(255),
  "status" "course_purchases_status_enum" NOT NULL DEFAULT 'pending',
  "purchasedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "admin_permissions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL UNIQUE,
  "manageCourses" INTEGER NOT NULL DEFAULT 0,
  "manageStudents" INTEGER NOT NULL DEFAULT 0,
  "manageContent" INTEGER NOT NULL DEFAULT 0,
  "manageAdmins" INTEGER NOT NULL DEFAULT 0,
  "manageSettings" INTEGER NOT NULL DEFAULT 0,
  "viewAnalytics" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "subscriptions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "plan" "subscriptions_plan_enum" NOT NULL DEFAULT 'free',
  "status" "subscriptions_status_enum" NOT NULL DEFAULT 'active',
  "startDate" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "endDate" TIMESTAMPTZ,
  "trialEndDate" TIMESTAMPTZ,
  "autoRenew" INTEGER NOT NULL DEFAULT 1,
  "stripeSubscriptionId" VARCHAR(255),
  "stripePriceId" VARCHAR(255),
  "stripeCustomerId" VARCHAR(255),
  "notes" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "payment_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "subscriptionId" INTEGER,
  "amount" INTEGER NOT NULL,
  "currency" VARCHAR(3) NOT NULL DEFAULT 'BRL',
  "status" "payment_history_status_enum" NOT NULL DEFAULT 'pending',
  "paymentMethod" VARCHAR(64),
  "stripePaymentIntentId" VARCHAR(255),
  "stripeInvoiceId" VARCHAR(255),
  "description" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "referrals" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "referrerId" INTEGER NOT NULL,
  "referredUserId" INTEGER,
  "referralCode" VARCHAR(32) NOT NULL,
  "status" "referrals_status_enum" NOT NULL DEFAULT 'pending',
  "planPurchased" "referrals_planPurchased_enum",
  "pointsAwarded" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "confirmedAt" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "pointsTransactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "amount" INTEGER NOT NULL,
  "type" "pointsTransactions_type_enum" NOT NULL,
  "description" TEXT,
  "referralId" INTEGER,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "cashbackRequests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "pointsAmount" INTEGER NOT NULL,
  "cashAmount" INTEGER NOT NULL,
  "status" "cashbackRequests_status_enum" NOT NULL DEFAULT 'pending',
  "paymentMethod" "cashbackRequests_paymentMethod_enum" NOT NULL,
  "pixKey" VARCHAR(255),
  "bankDetails" TEXT,
  "adminNotes" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "processedAt" TIMESTAMPTZ,
  "processedBy" INTEGER
);

CREATE TABLE IF NOT EXISTS "adminInvites" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "email" VARCHAR(320) NOT NULL,
  "role" "adminInvites_role_enum" NOT NULL DEFAULT 'admin',
  "token" VARCHAR(64) NOT NULL UNIQUE,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "invitedBy" INTEGER NOT NULL,
  "acceptedAt" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "appointments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "title" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "programType" VARCHAR(100),
  "startTime" TIMESTAMPTZ NOT NULL,
  "endTime" TIMESTAMPTZ NOT NULL,
  "duration" INTEGER NOT NULL,
  "status" "appointments_status_enum" NOT NULL DEFAULT 'scheduled',
  "location" VARCHAR(255),
  "notes" TEXT,
  "reminderSent" INTEGER NOT NULL DEFAULT 0,
  "cancelledBy" INTEGER,
  "cancelReason" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "userSettings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL UNIQUE,
  "emailNotifications" INTEGER NOT NULL DEFAULT 1,
  "smsNotifications" INTEGER NOT NULL DEFAULT 0,
  "pushNotifications" INTEGER NOT NULL DEFAULT 1,
  "reminderEmail" INTEGER NOT NULL DEFAULT 1,
  "reminderSms" INTEGER NOT NULL DEFAULT 0,
  "marketingEmails" INTEGER NOT NULL DEFAULT 0,
  "profilePublic" INTEGER NOT NULL DEFAULT 0,
  "shareProgress" INTEGER NOT NULL DEFAULT 0,
  "allowAnalytics" INTEGER NOT NULL DEFAULT 1,
  "darkMode" INTEGER NOT NULL DEFAULT 0,
  "fontSize" VARCHAR(20) NOT NULL DEFAULT 'medium',
  "highContrast" INTEGER NOT NULL DEFAULT 0,
  "reduceMotion" INTEGER NOT NULL DEFAULT 0,
  "language" VARCHAR(10) NOT NULL DEFAULT 'pt-BR',
  "timezone" VARCHAR(50) NOT NULL DEFAULT 'America/Sao_Paulo',
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "activityLogs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "action" VARCHAR(100) NOT NULL,
  "entity" VARCHAR(100),
  "entityId" INTEGER,
  "details" TEXT,
  "ipAddress" VARCHAR(45),
  "userAgent" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "notifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "title" VARCHAR(255) NOT NULL,
  "message" TEXT NOT NULL,
  "type" "notifications_type_enum" NOT NULL DEFAULT 'info',
  "read" INTEGER NOT NULL DEFAULT 0,
  "actionUrl" VARCHAR(500),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION "trg_set_users_on_update"() RETURNS trigger AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "trg_set_users_on_update" ON "users";
CREATE TRIGGER "trg_set_users_on_update" BEFORE UPDATE ON "users"
FOR EACH ROW EXECUTE FUNCTION "trg_set_users_on_update"();

CREATE OR REPLACE FUNCTION "trg_set_courses_on_update"() RETURNS trigger AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "trg_set_courses_on_update" ON "courses";
CREATE TRIGGER "trg_set_courses_on_update" BEFORE UPDATE ON "courses"
FOR EACH ROW EXECUTE FUNCTION "trg_set_courses_on_update"();

CREATE OR REPLACE FUNCTION "trg_set_course_modules_on_update"() RETURNS trigger AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "trg_set_course_modules_on_update" ON "course_modules";
CREATE TRIGGER "trg_set_course_modules_on_update" BEFORE UPDATE ON "course_modules"
FOR EACH ROW EXECUTE FUNCTION "trg_set_course_modules_on_update"();

CREATE OR REPLACE FUNCTION "trg_set_lessons_on_update"() RETURNS trigger AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "trg_set_lessons_on_update" ON "lessons";
CREATE TRIGGER "trg_set_lessons_on_update" BEFORE UPDATE ON "lessons"
FOR EACH ROW EXECUTE FUNCTION "trg_set_lessons_on_update"();

CREATE OR REPLACE FUNCTION "trg_set_enrollments_on_update"() RETURNS trigger AS $$
BEGIN
  NEW."lastAccessedAt" = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "trg_set_enrollments_on_update" ON "enrollments";
CREATE TRIGGER "trg_set_enrollments_on_update" BEFORE UPDATE ON "enrollments"
FOR EACH ROW EXECUTE FUNCTION "trg_set_enrollments_on_update"();

CREATE OR REPLACE FUNCTION "trg_set_subscription_plans_on_update"() RETURNS trigger AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "trg_set_subscription_plans_on_update" ON "subscription_plans";
CREATE TRIGGER "trg_set_subscription_plans_on_update" BEFORE UPDATE ON "subscription_plans"
FOR EACH ROW EXECUTE FUNCTION "trg_set_subscription_plans_on_update"();

CREATE OR REPLACE FUNCTION "trg_set_user_subscriptions_on_update"() RETURNS trigger AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "trg_set_user_subscriptions_on_update" ON "user_subscriptions";
CREATE TRIGGER "trg_set_user_subscriptions_on_update" BEFORE UPDATE ON "user_subscriptions"
FOR EACH ROW EXECUTE FUNCTION "trg_set_user_subscriptions_on_update"();

CREATE OR REPLACE FUNCTION "trg_set_course_reviews_on_update"() RETURNS trigger AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "trg_set_course_reviews_on_update" ON "course_reviews";
CREATE TRIGGER "trg_set_course_reviews_on_update" BEFORE UPDATE ON "course_reviews"
FOR EACH ROW EXECUTE FUNCTION "trg_set_course_reviews_on_update"();

CREATE OR REPLACE FUNCTION "trg_set_ebooks_on_update"() RETURNS trigger AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "trg_set_ebooks_on_update" ON "ebooks";
CREATE TRIGGER "trg_set_ebooks_on_update" BEFORE UPDATE ON "ebooks"
FOR EACH ROW EXECUTE FUNCTION "trg_set_ebooks_on_update"();

CREATE OR REPLACE FUNCTION "trg_set_user_profiles_on_update"() RETURNS trigger AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "trg_set_user_profiles_on_update" ON "user_profiles";
CREATE TRIGGER "trg_set_user_profiles_on_update" BEFORE UPDATE ON "user_profiles"
FOR EACH ROW EXECUTE FUNCTION "trg_set_user_profiles_on_update"();

CREATE OR REPLACE FUNCTION "trg_set_admin_permissions_on_update"() RETURNS trigger AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "trg_set_admin_permissions_on_update" ON "admin_permissions";
CREATE TRIGGER "trg_set_admin_permissions_on_update" BEFORE UPDATE ON "admin_permissions"
FOR EACH ROW EXECUTE FUNCTION "trg_set_admin_permissions_on_update"();

CREATE OR REPLACE FUNCTION "trg_set_subscriptions_on_update"() RETURNS trigger AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "trg_set_subscriptions_on_update" ON "subscriptions";
CREATE TRIGGER "trg_set_subscriptions_on_update" BEFORE UPDATE ON "subscriptions"
FOR EACH ROW EXECUTE FUNCTION "trg_set_subscriptions_on_update"();

CREATE OR REPLACE FUNCTION "trg_set_appointments_on_update"() RETURNS trigger AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "trg_set_appointments_on_update" ON "appointments";
CREATE TRIGGER "trg_set_appointments_on_update" BEFORE UPDATE ON "appointments"
FOR EACH ROW EXECUTE FUNCTION "trg_set_appointments_on_update"();

CREATE OR REPLACE FUNCTION "trg_set_userSettings_on_update"() RETURNS trigger AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "trg_set_userSettings_on_update" ON "userSettings";
CREATE TRIGGER "trg_set_userSettings_on_update" BEFORE UPDATE ON "userSettings"
FOR EACH ROW EXECUTE FUNCTION "trg_set_userSettings_on_update"();

COMMIT;